exports.cekResi = require('./cekResi')
exports.downloader = require('./downloader')
exports.meme = require('./meme')
exports.removebg = require('./remove-bg')
exports.urlShortener = require('./shortener')
